# Generated by Django 4.2.25 on 2025-10-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('image_url', models.CharField(max_length=3000)),
                ('category', models.CharField(max_length=50)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('date_published', models.DateField()),
            ],
        ),
    ]
