# Generated by Django 4.2.25 on 2025-11-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('views', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=700, unique=True)),
                ('image_url', models.CharField(blank=True, max_length=3000, null=True)),
                ('category', models.CharField(max_length=50)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('date_published', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('is_subscribed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Viewers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
