# Generated by Django 4.2.25 on 2025-10-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image_url',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
